export const TERMS_OF_SERVICE_VERSION = '1.0.0';
export const TERMS_OF_SERVICE_LAST_UPDATED = 'September 8, 2026';

export interface TermsSection {
  title: string;
  icon: string;
  content: string[];
}

export const TERMS_SECTIONS: TermsSection[] = [
  {
    title: '1. Purpose & Transformative Personal Format Shifting',
    icon: '📖',
    content: [
      'PaperEcho is an assistive productivity and accessibility tool designed to facilitate transformative, non-commercial format shifting of physical reading materials for private, personal use.',
      'In accordance with the Fair Use doctrine of the United States Copyright Act (17 U.S.C. § 107) and accessibility format-shifting principles (including 17 U.S.C. § 121), PaperEcho enables individuals who have legitimately acquired physical books or printed documents to convert their own printed text into temporary audio recordings for personal listening.',
    ],
  },
  {
    title: '2. User Ownership & Physical Possession Representation',
    icon: '⚖️',
    content: [
      'By using PaperEcho to scan, capture, or transcribe any printed work, you expressly warrant and represent that:',
      '• You legally own, purchase, or have lawful physical possession of the original printed book, textbook, or document being scanned.',
      '• The generated audiobook is created solely for your private, individual, non-commercial study, reading, or accessibility needs.',
      '• You will not use PaperEcho to circumvent digital rights management (DRM) or digitize materials for commercial distribution.',
    ],
  },
  {
    title: '3. Strict Prohibition Against Distribution & Sharing',
    icon: '🚫',
    content: [
      'PaperEcho is not a digital library, distribution service, or file-sharing network. You agree that:',
      '• You shall NOT copy, share, transmit, broadcast, publicize, sell, rent, or distribute any audio recordings, OCR transcripts, or derivative files generated by the service to any third party.',
      '• You shall NOT upload generated audio or transcriptions to public file hosts, torrent trackers, social media, or audio distribution platforms.',
      '• Any violation of this non-distribution covenant results in immediate termination of account access.',
    ],
  },
  {
    title: '4. Ephemeral Cloud Storage & Automated 7-Day Purge',
    icon: '⏳',
    content: [
      'To prevent the permanent accumulation or hosting of copyrighted materials on cloud servers, PaperEcho enforces an automated ephemeral storage lifecycle:',
      '• Synthesized audio files (.wav) are temporary working copies stored in user-isolated cloud storage and are automatically permanently deleted after seven (7) days.',
      '• Raw video recordings captured for page scanning are processed ephemerally and discarded immediately following text extraction.',
      '• Users retain their chapter metadata and may re-narrate their physical copies on-demand whenever they wish to listen again.',
    ],
  },
  {
    title: '5. Audible Forensics & Security Watermarking',
    icon: '🔒',
    content: [
      'To prevent unauthorized redistribution and protect copyright holders, PaperEcho embeds a tamper-evident audible forensic watermark at the beginning of each generated audio file.',
      'This watermark voiceover explicitly states the book title, author, and your registered account identity (e.g., email address), confirming that the file is an authorized, non-transferable personal copy.',
      'Attempting to edit, remove, or obscure this watermark is a material violation of these Terms.',
    ],
  },
  {
    title: '6. AI Processing & Third-Party Services',
    icon: '🤖',
    content: [
      'PaperEcho utilizes state-of-the-art multimodal artificial intelligence models (including Google Gemini API) to perform optical character recognition (OCR), text cleaning, and text-to-speech (TTS) synthesis.',
      'Transcribed text and video frames are submitted to AI processors strictly for the purpose of generating your personal reading and are not used to train public machine learning models without consent.',
    ],
  },
  {
    title: '7. DMCA & Copyright Safe Harbor Policy',
    icon: '🛡️',
    content: [
      'PaperEcho respects the intellectual property rights of authors and publishers. If you are a copyright owner and believe that content processed on the service infringes your rights, please submit a formal DMCA notification to: legal@paperecho.app.',
      'Upon receipt of a valid notice, PaperEcho will promptly remove or disable access to the relevant content in accordance with 17 U.S.C. § 512.',
    ],
  },
  {
    title: '8. Disclaimer of Warranties & Limitation of Liability',
    icon: '📄',
    content: [
      'PaperEcho is provided on an "AS IS" and "AS AVAILABLE" basis without warranties of any kind regarding OCR accuracy, voice synthesis perfection, or uninterrupted service availability.',
      'In no event shall PaperEcho, its developers, or its affiliates be liable for any indirect, incidental, special, or consequential damages resulting from your use of the application.',
    ],
  },
];
